### ISSUE TITLE
Cppcheck version 2.13 has been released

### ISSUE THREAD

**Issue by orbitcowboy** [fleschutz/CWTS#2]
I noticed that the Cppcheck version that is used is pretty outdated. The latest stable version has is (currently) 2.13.0:
-  https://github.com/danmar/cppcheck/releases/tag/2.13.0

It's worth to update, since a lot of new checks and improvements have been integrated.

**Comment by fleschutz** [comment]
Hi orbitcowboy, you're right. I was using cppcheck 2.3 as a snap (latest channel) but it has never been updated. Now, I retested it with cppcheck 2.11 (the latest for Ubuntu 23.10) and updated the results. Thank you very much for the hint.
